### PR TITLE
report different states to azure test plans

### PR DESCRIPTION
**Pull request by joerg1985**
This PR implements the change described in #38 without the option to configure the mapping.

I have no NodeJs IDE or the option to test this changes locally, so please review.

### CODE REVIEW

**Comment by alexneo2003** [comment]
@joerg1985 I appreciate you work
I am added a little bit fixes in you code but I not added config mapping
also I published package as beta, check out 
```bash 
@alex_neo/playwright-azure-reporter@1.6.0-beta.0
```

**Comment by joerg1985** [comment]
@alexneo2003 

thank you, will test it in the next days and give feedback.

**Comment by joerg1985** [comment]
`skipped = 'Not Applicable',` should be `skipped = 'NotApplicable',` looks like we need to hit a Enum name here.

All the enums are listed [here](https://learn.microsoft.com/en-us/azure/devops/report/analytics/entity-reference-test-plans?view=azure-devops#testoutcome-enumerated-type-members), so we can map other values too:
 - `timeout` to `Timeout`
 - `interrupted` to `Aborted`

**Comment by joerg1985** [comment]
@alexneo2003 could you please create a new beta with the latest fixes?

**Comment by alexneo2003** [comment]
> @alexneo2003 could you please create a new beta with the latest fixes?

```bash
@alex_neo/playwright-azure-reporter@1.6.0-beta.1
```

**Comment by joerg1985** [comment]
I had a look at the last runs of the pipeline and the results look good, this could be merged.

The only thing to notice is that the 'Aborted' status does not update the state shown, but it will be listed in the details.
To check this i had to call the API with the 'Aborted' status, as this state is IMHO not reachable when running in the CI.

PS: i think the 'colors' dependency could be removed or did i miss the usage in the code?
https://github.com/alexneo2003/playwright-azure-reporter/blob/main/package.json#L43

**Pull request merged**
